# Generated by Django 3.0.3 on 2020-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='h_type',
            field=models.CharField(choices=[('1', 'โรงพยาบาล'), ('3', 'ศูนย์บริการสาธารณสุข'), ('4', 'คลินิก')], max_length=255),
        ),
    ]
