# Generated by Django 3.0.3 on 2020-09-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20200903_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='h_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
