# Generated by Django 3.0.3 on 2020-09-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20200905_1611'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hospitals',
            unique_together={('label', 'code')},
        ),
    ]
