# Generated by Django 3.0.3 on 2020-09-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_auto_20200905_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
